//Begin
// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract keeperCar is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;
 
   // Metadata information for each stage of the NFT on IPFS.
    string[] IpfsUri = [
        "https://bafkreiei6mcthofnx76clkkw3yt3svw7jpqsnq5patqpyhqbmo7vcpg5ki.ipfs.nftstorage.link/",
        "https://bafkreiezk2woelj2txrq4iafdraomv7ntazuorslfjudauxgwpqmydmij4.ipfs.nftstorage.link/",
        "https://bafkreigesqjkb6zzhl3ubxmi64bf3l5m4k3hajdqztvnbbcr2qxiwdwvx4.ipfs.nftstorage.link/",
        "https://bafkreiceyxpeu3c52rdjggbhfe6xx5d4og4uyxsttbsswuebogk3nogvse.ipfs.nftstorage.link/",
        "https://bafkreihch2xuudmkwfg2qz3ywi4zfpkm5qjhajjiiknf2f4kq3gy5jdjfe.ipfs.nftstorage.link/"
    ]; 

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint _interval) ERC721("Car Platzi", "cPLTZ") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (CarStage(tokenId) >= 4) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            growCar(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function growCar(uint256 _tokenId) public {
        if(CarStage(_tokenId) >= 4){return;}
        // Get the current stage of the Car and add 1
        uint256 newVal = CarStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the Car growth
    function CarStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // Car 1
        if (compareStrings(_uri, IpfsUri[0])) {
            return 0;
        }
        // Car 2
        if (compareStrings(_uri, IpfsUri[1]) ){
            return 1;
        }
        // Car 3
        if (compareStrings(_uri, IpfsUri[2]) ){
            return 2;
        }
        // Car 4
        if (compareStrings(_uri, IpfsUri[3]) ){
            return 3;
        }
        // Must be Car 5
        return 4;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
//End
