// SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;


import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract GokuDynamicNFT is ERC721, ERC721URIStorage, Ownable, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    string [] uriData = ["https://gateway.pinata.cloud/ipfs/QmZ733hWgVF9TgqLXsVhRsZC3tL2FvtoWjM3u9XhMSFthW",
                         "https://gateway.pinata.cloud/ipfs/QmTggdbqDzStbFCzJMT7CcwUZkC8jgvPrn3r2RoapBdwoD",
                         "https://gateway.pinata.cloud/ipfs/QmUBwsLdrUD3EazrtvJxG4ZJjcr6HjzH34mkQNWfCMRo6B",
                         "https://gateway.pinata.cloud/ipfs/QmZCqHmYkosvcF22cfXMxU3XDFyhwbQYHeiiSXbtTk4WRN",
                         "https://gateway.pinata.cloud/ipfs/QmcxbbWnRogWFtvdo2ViKnpHeiruaEpjW4H1X4bQuZXjWR",
                         "https://gateway.pinata.cloud/ipfs/QmcUsFqy5wyi6B42TPpwKDpftG7cfrZRt4LCTexsbqPTUf",
                         "https://gateway.pinata.cloud/ipfs/QmRC65SDNhr4SdPXepJpNrH2Qc33dQkxqNUMem35jCXtbJ"];

    Counters.Counter private _tokenIdCounter;

    uint256 lastTimeStamp; 
    uint256 interval;


    constructor(uint _interval) ERC721("GokuNFT", "GTK") {
        interval = _interval;
        lastTimeStamp = block.timestamp;       
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = _tokenIdCounter.current() - 1;
        bool done;
        if (gokuPhase(tokenId) >= 6) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = _tokenIdCounter.current() - 1;
            evolGoku(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }


    function safeMint(address to) public onlyOwner {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, uriData[0]);
    }

    function changeData(uint256 _tokenId) public{
        _setTokenURI(_tokenId, uriData[1]);
    }


    function evolGoku(uint256 _tokenId) public {
        if(gokuPhase(_tokenId) >= 6){return;}
        // Get the current stage of the flower and add 1
        uint256 newVal = gokuPhase(_tokenId) + 1;
        // store the new URI
        string memory newUri = uriData[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function gokuPhase(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // Normal Goku
        if (compareStrings(_uri, uriData[0])) {
            return 0;
        }
        // Goku SSJ
        if (
            compareStrings(_uri, uriData[1]) 
        ) {
            return 1;
        }
        // Goku SSJ2
        if (
            compareStrings(_uri, uriData[2]) 
        ) {
            return 2;
        }
        // Goku SSJ3
        if (
            compareStrings(_uri, uriData[3]) 
        ) {
            return 3;
        }
        // Goku Dios
        if (
            compareStrings(_uri, uriData[4]) 
        ) {
            return 4;
        }
        // Goku Dios - Blue
        if (
            compareStrings(_uri, uriData[5]) 
        ) {
            return 5;
        }
            
        // Must be a Goku Ultra Instinct
        return 6;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b) public pure returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) == keccak256(abi.encodePacked((b))));
    }

    // The following functions are overrides required by Solidity.

    function _burn(uint256 tokenId) internal override(ERC721, ERC721URIStorage) {
        super._burn(tokenId);
    }

    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}