//Begin
// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract MoonPhaseContract is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;
 
   // Metadata information for each stage of the NFT on IPFS.
     string[] IpfsUri = [
        "https://gateway.pinata.cloud/ipfs/Qmf6NYdWBmjWxHpfmyo7W9zRpneHD15DXB3KiSoht24erA",
        "https://gateway.pinata.cloud/ipfs/Qme9cqnwAoNpXJv7p1JvAcnd55HQrky1LxmcoyekHH14yH",
        "https://gateway.pinata.cloud/ipfs/QmTjJS8SyqPp5u7awYZrvV2ELcJyG3hqH7rnTACV95bjRm",
        "https://gateway.pinata.cloud/ipfs/QmZYCDgP34UgNm8vE3kDqRD4EnNEWhnRG64BL4z5xngrbv",
        "https://gateway.pinata.cloud/ipfs/QmP494buZNbfEd8S4ewy5Gv3rRyATgY7XpqaRp4vYhty6A",
        "https://gateway.pinata.cloud/ipfs/QmaRZtKnqtvph5H2Tj2WS67fcY4zdnqtMPVpSneEXXuYWA"
    ]; 

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint _interval) ERC721("MoonPhase", "MOPS") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (moonPhase(tokenId) >= 4) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            changePhase(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function changePhase(uint256 _tokenId) public {
        if(moonPhase(_tokenId) >= 2){return;}
        // Get the current stage of the flower and add 1
        uint256 newVal = moonPhase(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function moonPhase(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // Luna Nueva
        if (compareStrings(_uri, IpfsUri[0])) {
            return 0;
        }
        // Cuarto Creciente
        if (
            compareStrings(_uri, IpfsUri[1]) 
        ) {
            return 1;
        }
        // Creciente Convexa
        if (
            compareStrings(_uri, IpfsUri[2]) 
        ) {
            return 2;
        }
        // Luna Llena
        if (
            compareStrings(_uri, IpfsUri[3]) 
        ) {
            return 3;
        }
        // Menguante Convexa
        if (
            compareStrings(_uri, IpfsUri[4]) 
        ) {
            return 4;
        }
        // Cuarto Menguante
        return 5;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
//End