//Begin
// SPDX-License-Identifier: MIT
pragma solidity 0.8.6;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract Figuras is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;
 
   // Metadata information for each stage of the NFT on IPFS.
   string[] IpfsUri = [ 
       "https://gateway.pinata.cloud/ipfs/QmW2tt74KPALJzR2tX17y7qkjRDrBXKjderj83gshJ4g6R", 
       "https://gateway.pinata.cloud/ipfs/QmVLvHQVvGRRrDUowu3UuVMhT2uz7eo1U6KoADt22tnwKA", 
       "https://gateway.pinata.cloud/ipfs/QmbWaGTGSPoQzxE7H2M65w5FETRah8CHMeK4ED4p3VAKV8",
       "https://gateway.pinata.cloud/ipfs/QmVSSN7GTNEhEzmKKcHny41N7Mff7qxYuGN43d5QWcBAdr", // pentagono
       "https://gateway.pinata.cloud/ipfs/QmQ3bE8UPq8X2N6gM1nEY1beES7goqqnbuCGBv2xmHeVDH" // hexagono
       ];

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint _interval) ERC721("Figuras", "FG") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (figureStage(tokenId) >= 4) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            evolveFigure(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function evolveFigure(uint256 _tokenId) public {
        if(figureStage(_tokenId) >= 4){return;}
        // Get the current stage of the flower and add 1
        uint256 newVal = figureStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function figureStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // Triangulo
        if (compareStrings(_uri, IpfsUri[0])) {return 0;}
        // Cuadrado
        if (compareStrings(_uri, IpfsUri[1])) {return 1;}
        // Circulo
        if (compareStrings(_uri, IpfsUri[2])) {return 2;}
        // Pentagono
        if (compareStrings(_uri, IpfsUri[3])) {return 3;}
        // Hexagono
        return 4;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
//End