// SPDX-License-Identifier: MIT
pragma solidity ^0.8.6;
import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract TIMBERNFT is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;
     string[] uriData = [
        "https://gateway.pinata.cloud/ipfs/QmZnSH1ieNtxBhposr2X9cYadenf2NoSpz9QD4zetUQWEe",
        "https://gateway.pinata.cloud/ipfs/QmUcA7Ln1PKcQibTRc5PSwJqAEV4V5AqyGuWVQFZCc9BCB",
        "https://gateway.pinata.cloud/ipfs/Qmas6ZQJSmRRRzqp1jmhA4LYVmJFXp4DyaY3Lw4Ei5cceC",
        "https://gateway.pinata.cloud/ipfs/QmcTcEAzP2ScPs3Rvhk59CurvGW7CJE3k4kDNTVao1MPWU"
    ]; 
    uint256 lastTimeStamp;
    uint256 interval;

    Counters.Counter private tokenIdCounter;

    constructor(uint _interval) ERC721("TIMBERNFT", "TLT") {
         interval = _interval;
        lastTimeStamp = block.timestamp;
    }

     function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (woodType(tokenId) >= 2) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            changeWood(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public  {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, uriData[0]);
    }

     function changeWood(uint256 _tokenId) public {
        if(woodType(_tokenId) >= uriData.length){return;}
        // Get the current stage of the flower and add 1
        uint256 newVal = woodType(_tokenId) + 1;
        // store the new URI
        string memory newUri = uriData[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function woodType(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // choiba wood
        if (compareStrings(_uri, uriData[0])) {
            return 0;
        }
        // sapan wood
        if (
            compareStrings(_uri, uriData[1]) 
        ) {
            return 1;
        }
        // chanul wood
         if (
            compareStrings(_uri, uriData[2]) 
        ) {
            return 2;
        }
        // cedro wood
        return 3;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
//End
