// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract keeperCertificate is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;
 
   // Metadata information for each stage of the NFT on IPFS.
    string[] IpfsUri = [
        "https://gateway.pinata.cloud/ipfs/QmXnwvjLUqcq8EEcqGRRpgW1HnZYzWoBnBBT9py9gu6dw6",
        "https://gateway.pinata.cloud/ipfs/Qmaiufvd3QQJTfrG3JaNVpqN5AwN21oPm3VniyoJSQiSo3",
        "https://gateway.pinata.cloud/ipfs/QmXADZyTLoEKy1VgzHuZdxc12TFLSpTpGq5rV8qjb2wT6T",
        "https://gateway.pinata.cloud/ipfs/QmakoH5aMxpC3H4eumh16gwXq382apbByEaiHDUakd27Sz",
        "https://gateway.pinata.cloud/ipfs/QmYT2UrUmFx1XCpgdTcjjCar1bcWTWjMQecgENBhYgLhi6"
    ]; 

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint _interval) ERC721("Certification U3 University", "cu3") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(bytes calldata /* checkData */) external view override returns (bool upkeepNeeded, bytes memory /* performData */) {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (certificationStage(tokenId) >= 4) {
            done = true;
        }
        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);        
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(bytes calldata /* performData */) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval ) {
            lastTimeStamp = block.timestamp;            
            uint256 tokenId = tokenIdCounter.current() - 1;
            updateCertification(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function updateCertification(uint256 _tokenId) public {
        if(certificationStage(_tokenId) >= 4){return;}
        // Get the current stage of the certification and add 1
        uint256 newVal = certificationStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the certification
    function certificationStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // 1st phase
        if (compareStrings(_uri, IpfsUri[0])) {
            return 0;
        }
        // 2nd phase
        if (
            compareStrings(_uri, IpfsUri[1]) 
        ) {
            return 1;
        }
        // 3nd phase
        if (
            compareStrings(_uri, IpfsUri[2]) 
        ) {
            return 2;
        }
        // 4th phase
        if (
            compareStrings(_uri, IpfsUri[3]) 
        ) {
            return 3;
        }
        // 5th phase
        return 4;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}